version: "3.8"

services:
  mysql:
    container_name: gridge-mysql
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gridge
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234
    ports:
      - "33066:3306" # 개발용으로만 사용, 실제 운영환경에서는 주석 처리
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/test-data.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-net
    healthcheck:
      # root 패스워드는 환경변수 재사용
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -uroot -p$${MYSQL_ROOT_PASSWORD} || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  app:
    container_name: gridge-server
    image: dockerhayoon/gridge-server:latest
    ports:
      - "8080:8080"
    environment:
      # application.properties에서 설정한 환경변수와 다르기 때문에 새로운 값으로 오버라이드
      # 이렇게 설정하면 application.properties에 설정한 환경변수는 무시됨
      # 실제 운영환경에서는 하드코딩하지 않고 변수로 설정하여 사용
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=gridge
      - DB_USERNAME=admin
      - DB_PASSWORD=1234
      - JWT_SECRET=gridge_secret_key_this_is_very_very_long_secret_key_for_jwt_token_security_minimum_256_bits
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-net
    restart: unless-stopped

# 볼륨 설정 : DB 데이터를 컨테이너 생명주기와 분리해 영속 저장소 확보
volumes:
  mysql_data:

networks:
  app-net:
    driver: bridge
